import streamlit as st
import pandas as pd
import sqlite3
import plotly.express as px


# ==================================
# PAGE CONFIG
# ==================================

st.set_page_config(
    page_title="Local Food Wastage Management",
    page_icon="🍲",
    layout="wide"
)


# ==================================
# DATABASE
# ==================================

@st.cache_resource
def get_connection():

    return sqlite3.connect(
        "local_food_wastage.db",
        check_same_thread=False
    )


conn=get_connection()


@st.cache_data
def load_data():

    pd.read_csv(
        "providers_data.csv"
    ).to_sql(
        "providers",
        conn,
        if_exists="replace",
        index=False
    )

    pd.read_csv(
        "receivers_data.csv"
    ).to_sql(
        "receivers",
        conn,
        if_exists="replace",
        index=False
    )

    pd.read_csv(
        "food_listings_data.csv"
    ).to_sql(
        "food",
        conn,
        if_exists="replace",
        index=False
    )

    pd.read_csv(
        "claims_data.csv"
    ).to_sql(
        "claims",
        conn,
        if_exists="replace",
        index=False
    )


load_data()


food=pd.read_sql(
"SELECT * FROM food",
conn
)

claims=pd.read_sql(
"SELECT * FROM claims",
conn
)

providers=pd.read_sql(
"SELECT * FROM providers",
conn
)

receivers=pd.read_sql(
"SELECT * FROM receivers",
conn
)


# ==================================
# SIDEBAR
# ==================================

page=st.sidebar.radio(

"Navigation",

[
"Dashboard",
"Providers",
"Receivers",
"Claims",
"Manage Food",
"SQL Analysis"
]

)


st.sidebar.title(
"🛠️ Dashboard Control Panel"
)


city=st.sidebar.multiselect(
"📍 Filter by City Location",
sorted(food["Location"].dropna().unique())
)


provider=st.sidebar.multiselect(
"🏢 Filter by Provider Type",
sorted(food["Provider_Type"].dropna().unique())
)


meal=st.sidebar.multiselect(
"⏰ Filter by Meal Time Windows",
sorted(food["Meal_Type"].dropna().unique())
)


diet=st.sidebar.multiselect(
"🥦 Filter by Dietary Food Type",
sorted(food["Food_Type"].dropna().unique())
)


st.sidebar.markdown("---")


st.sidebar.subheader(
"💾 Operational Vector Extractors"
)


st.sidebar.info(
"""
💡 Tip:

Use filters to quickly generate clean data distributions for target cities or high-priority dietary profiles!
"""
)


filtered=food.copy()


if city:
    filtered=filtered[
        filtered["Location"].isin(city)
    ]


if provider:
    filtered=filtered[
        filtered["Provider_Type"].isin(provider)
    ]


if meal:
    filtered=filtered[
        filtered["Meal_Type"].isin(meal)
    ]


if diet:
    filtered=filtered[
        filtered["Food_Type"].isin(diet)
    ]


filtered_claims=claims.merge(
filtered[["Food_ID"]],
on="Food_ID",
how="inner"
)


# ==================================
# DASHBOARD
# ==================================

if page=="Dashboard":


    st.title(
"🍲 Local Food Wastage Management System Dashboard"
)

    st.caption(
"Production Analytical Workspace | Real-Time Supply & Demand Matrix Optimization"
)


    k1,k2,k3,k4=st.columns(4)


    k1.metric(
"📦 Total Unique Food Items Listed",
filtered["Food_ID"].nunique()
)


    k2.metric(
"📊 Aggregate Food Volume",
int(filtered["Quantity"].sum())
)


    completed=filtered_claims[
filtered_claims["Status"]=="Completed"
]


    k3.metric(
"✅ Successfully Secured Claims",
len(completed)
)


    rate=0


    if len(filtered_claims)>0:

        rate=(
            len(completed)
            /
            len(filtered_claims)
        )*100


    k4.metric(
"📈 Operational Claim Success Rate",
f"{rate:.2f}%"
)


    st.divider()


    st.subheader(
"📊 Visual Distribution Metrics & Performance Trends"
)


    left,right=st.columns(2)


    with left:

        st.markdown(
"### Total Food Quantity Available by City Location"
)

        chart=(
            filtered
            .groupby(
                "Location"
            )
            ["Quantity"]
            .sum()
            .reset_index()
        )


        fig=px.bar(
            chart,
            x="Location",
            y="Quantity",
            color="Location"
        )


        st.plotly_chart(
            fig,
            use_container_width=True
        )


    with right:


        st.markdown(
"### Demand Velocity Breakdown (Total Claims Generated by Meal Type)"
)


        demand=(
            filtered_claims
            .merge(
                filtered,
                on="Food_ID"
            )
            .groupby(
                "Meal_Type"
            )
            .size()
            .reset_index(
                name="Claims"
            )
        )


        fig=px.pie(
            demand,
            names="Meal_Type",
            values="Claims",
            hole=.6,
            color="Meal_Type"
        )


        st.plotly_chart(
            fig,
            use_container_width=True
        )


    left2,right2=st.columns(2)


    with left2:


        st.markdown(
"### Volume Stream Profile (Dietary Composition Matrix)"
)


        group=(
            filtered
            .groupby(
                [
                    "Meal_Type",
                    "Food_Type"
                ]
            )
            .size()
            .reset_index(
                name="Count"
            )
        )


        fig=px.bar(
            group,
            x="Meal_Type",
            y="Count",
            color="Food_Type",
            barmode="group"
        )


        st.plotly_chart(
            fig,
            use_container_width=True
        )


    with right2:


        st.markdown(
"### Active System Claims Operations Tracking Status"
)


        status=(
            filtered_claims
            ["Status"]
            .value_counts()
            .reset_index()
        )


        status.columns=[
            "Status",
            "Count"
        ]


        fig=px.bar(
            status,
            x="Count",
            y="Status",
            orientation="h",
            color="Status"
        )


        st.plotly_chart(
            fig,
            use_container_width=True
        )


    st.divider()


    st.subheader(
"🔍 Master Operations Records Search & Logistics Engine"
)


    search=st.text_input(
"💡 Query Vector Search (Enter Food Item Name, Provider Name, or Status to filter)..."
)


    table=filtered.merge(
        filtered_claims,
        on="Food_ID",
        how="left"
    )


    if search:

        table=table[
            table
            .astype(str)
            .apply(
                lambda x:
                x.str.contains(
                    search,
                    case=False
                )
            )
            .any(axis=1)
        ]


    st.dataframe(
        table,
        use_container_width=True,
        height=550
    )


elif page=="Providers":

    st.dataframe(
        providers,
        use_container_width=True
    )


elif page=="Receivers":

    st.dataframe(
        receivers,
        use_container_width=True
    )


elif page=="Claims":

    st.dataframe(
        claims,
        use_container_width=True
    )


elif page=="Manage Food":

    st.dataframe(
        filtered,
        use_container_width=True
    )


elif page=="SQL Analysis":

    st.title(
"SQL Analysis"
)

    st.dataframe(
        food
    )


st.divider()

st.caption(
"Developed using Streamlit + SQLite"
)


